apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    app: front-app
    name: front-service
spec:
  type: NodePort
  selector:
    app: front-app
  ports:
  - port: 3000
    targetPort: 3000